### ISSUE TITLE
Android: Final Fantasy XII

### ISSUE THREAD

**Issue by Thunder07** [jpd002/Play-#105]
I recall reading on last weeks Update that you mentioned FFXII is running but slowly on android.
I've tried but it seems the game stops at the same spot everytime.
after the initial Intro, I select New Game, Wait for Final Fantasy XII Logo followed by the green mist/warp looking screen this is where it freezes, the f/s & dc/f are still moving and ranging between 6-10fps 126-140 dc/f.
interacting with the same cause these values to flucate alot, even as high up dc/f to 2000 (i think even 5000 at some stage).

Anyways, I grabbed few log cats and they seem consistent enough:
Official release 13/07/2015: http://pastebin.com/mtmhKBHi
unofficial build: http://pastebin.com/38Yx11GG

in the official release logcat, I think this "GL_OUT_OF_MEMORY" appeared earlier in the mist of all the repeating logs.
also in the offical release the game often crashes at this point but it prints few "EGL_CONTEXT_LOST" before doing so, while the unoffical build just keeps on spitting "EGL_CONTEXT_LOST"

**Comment by LoungeKatt** [comment]
Have you tried editing the manifest and running with glEs 2? The code is set to use 2 and only being forced to 3 by the manifest. It may reduce the chance for EGL errors with stable drivers.

**Comment by Thunder07** [comment]
I did, although the log provided is with the manifest set to 3, its seems its still using 2? "Adreno-ES20"
but even with it set to 2, still the same problem at the same location.

I'm gonna do a quick clean build just to be sure.

**Comment by LoungeKatt** [comment]
The code calls for a 2 context. I submitted a pull to change the manifest. I was also playing around with updating the code to use 3, but that takes a lot longer.

**Comment by Thunder07** [comment]
ok so its the same with the manifest set to 2, but for the 1st run I didn't get any of the warnings ("EGL_CONTEXT_LOST" or "GL_OUT_OF_MEMORY"), and the game exited but on the 2nd run it froze and just spammed "EGL_CONTEXT_LOST".
http://pastebin.com/QqWhE0CD
http://pastebin.com/ZeJvNWkC

**Comment by itsmachotime5** [comment]
@LoungeKatt I don't care what the code is calling; it's immature. Don't make me regret coming here.

I'll delete my comment if you delete yours.

**Comment by jpd002** [comment]
My guess is that the vertex buffer for rendering primitives gets too big. The culprit is probably that line https://github.com/jpd002/Play-/blob/10ac9246eae7ff5411208816dbe371609dac09af/Source/gs/GSH_OpenGL/GSH_OpenGL.cpp#L1670. It's pretty stupid at the moment, because the buffer's size is unbounded, I need to improve that.

@LoungeKatt I'll take a look at my context creation code again, but I built everything with GLES 3.0 in mind.

**Comment by LoungeKatt** [comment]
It probably works on either, but then it probably works on either.

**Comment by typewritershows** [comment]
@LoungeKatt Stop being immature. I don't care who started it

**Comment by typewritershows** [comment]
Abuse lasts a lifetime.

**Comment by Thunder07** [comment]
@jpd002 I really have no knowledge of GL (some basic enough knowledge in C, mostly transferable from java), but I can always mess around with the code.
I added the code below after if(m_vertexBuffer.empty()) return; to clear out big buffer vertex and the results is variable still.
```
	if (sizeof(PRIM_VERTEX) * m_vertexBuffer.size() >= 504) {
		m_vertexBuffer.clear();
		return;
	}
```
I get this instead of the green/mist screen (since i cleared out all most of the vertex?)
![screenshot_2015-07-18-02-39-46](https://cloud.githubusercontent.com/assets/5013823/8759969/0a527ce8-2cfd-11e5-93dc-0bc1561ee554.png)

and few time (after the mostly invisible/distorted setting menu which immediately proceeds the screenshot, which if i dont react to quickly or even attempting to navigate it crashes the game) I get what looks like the start of the new cut scene with immediate game exit.

so unless im missing something, its not entirely the buffers fault?

**Comment by abhidibada** [comment]
@jpd002 why you dont reply or help me with my issues? I emailed you and asked for help on G+ but moderators delete it and you are very rude because you interact with other developers on G+ and this site but you won't help me or many of other supporters/testers/people who actually help the emu too.

**Comment by jpd002** [comment]
@abhidibada Sorry, my time is limited and I can't answer everyone. Can you open a new issue on GitHub with a description of your problem so we can work it out? Thanks.

**Comment by abhidibada** [comment]
no I wont bother because you are clearly too busy on gooogle hangouts with developers. typical emu developer who only gives a shit about there developer buddys and never cares about all the thousands of people who test games for you, do bug reports and even analyze/fix problem for you

**Comment by edwardmx96** [comment]
Personally, I am grateful that someone is finally making a ps2 emu for android. @jpd002 keep up the good work. Thank you for fixing the KH2 issue. I can imagine how stressful it is to be working on so many issues at once. Take it easy. @abhidibada it's not an easy task I can imagine for the developer to be stretched in so many places at once. The emulator will get there soon.

**Comment by LoungeKatt** [comment]
@abhidibada By starting a new issue, you get a whole thread to talk about it. It won't get lost in a sea of posts and it will only get merged with related issues. These developer buddies you speak of may have answers as well, but most likely aren't reading @jpd002's email.

Your post may have been deleted on Google+ if it broke a rule. One of them happens to be that you shouldn't post that a game doesn't work. Instead, you should open or add to an issue on github. It's meant to help get the attention you need as soon as possible.

**Comment by acocalypso** [comment]
Hi I tested this game with latest build on my Oneplus one with cyanogenmod nightly and I just get a black screen.

**Comment by Thunder07** [comment]
just a quick update, I know you didn't touch anything to do with the buffer or vertex but from the current weekly (25th/07) I now get this screen, which takes place slightly ahead of the usual green/mist screen (which often freezes or just crashes the emulator activity).

![screenshot_2015-07-28-16-24-48](https://cloud.githubusercontent.com/assets/5013823/8937980/a51d029e-3553-11e5-8b5b-34729dcd4df3.png)

again, shorty after this screen the game crashes,(bad vertex?) with similar logs to the ones posted earlier.
could this be due to bad drivers?(though they should be relatively updated).
I've also got Odin Sphere to test it, and the game still crashes before making it to the game play.

looking at this game play video https://www.youtube.com/watch?v=DSc-Cp58izE
the green/mist seems to be confined within the warrior.
so there is an error in drawing/rendering (as if the black blocks wasn't enough of a hint :p)

to add to what you said about earlier about buffer size been unbounded, on that same referred line you posted, you have this "sizeof(PRIM_VERTEX) * m_vertexBuffer.size()" could their product be breaking the integer limit thus crashing emulator?
to add to this after the crash I always get "W/RenderThread( 8615): type=1701 audit(0.0:31410): auid=4294967295 uid=10223 gid=10223 ses=4294967295 subj=u:r:untrusted_app:s0 reason="memory violation" sig=11"
memory violation in this context could mean to anything, I also got this when using I tried to implement the getserial function and used a string to store the serial without 1st initiating that string.

sorry for the long post.

**Comment by jpd002** [comment]
I did not investigate the crash issue yet, but as for the black squares, it has been fixed (partially) by 07ae4517959b81faeffebcf04ea61071946af7f8.

**Comment by Thunder07** [comment]
Ah great, I didn't get the time to check it out and the game never made it this far for me to even see them. 

Anyway, my post was mainly to stir some thoughts, it really makes no difference until we gain few more fps.

If I have any more thoughts, I'll be sure to spam you :p

**Comment by jpd002** [comment]
@Thunder07 Spam away :) Ideas are always good.

**Comment by Thunder07** [comment]
some update, I switched to the latest source built qualcomm kernel and it seems the full screen green-mist is solved, the warrior appears correctly with all the vertex in him.

however, the text is is garbled or more like superimposed over other text, but its still readable.
as for the black boxes, they still appear but with a white, almost glowing circle in there centres (i suspect its just the incompleted alpha?).

if you want me to, i can always return back to older rom/kernel for testing.
just so you can add more safety checks or so.

**Comment by jpd002** [comment]
The text problem is "normal". I still need to figure out what it is, but I think it's related to the special texture addressing modes that are not implemented yet in the shader on GLES.

**Comment by Thunder07** [comment]
cool, I
![screenshot_2015-08-05-23-55-23](https://cloud.githubusercontent.com/assets/5013823/9124748/ce8dad82-3c91-11e5-8adc-48667197fea5.png)
![screenshot_2015-08-06-00-14-44](https://cloud.githubusercontent.com/assets/5013823/9124751/ceb5814a-3c91-11e5-98d7-d5325b43b387.png)
![screenshot_2015-08-06-07-36-06](https://cloud.githubusercontent.com/assets/5013823/9124753/ceb74048-3c91-11e5-91a9-56e7e991334a.png)
![screenshot_2015-08-06-07-45-23](https://cloud.githubusercontent.com/assets/5013823/9124752/ceb5eb80-3c91-11e5-985e-efbde44cddc4.png)
![screenshot_2015-08-06-07-48-04](https://cloud.githubusercontent.com/assets/5013823/9124750/ceaea302-3c91-11e5-9dfd-70c50466e72d.png)

**Comment by acocalypso** [comment]
If Im right dc stands for draw calls. Every visible object in a scene generates a draw call. The higher the call the slower the rendering. Its possible to reduce those by patching assets/textures into an atlas. This will increase the speed. Im using this method alot in game development. Maybe this info is usefull

**Comment by jpd002** [comment]
Yeah, "dc" stands for draw calls. The current algorithm batches polygon sequences that share the same render state (textures, but also alpha blending, depth test, alpha test, etc.). I'm betting FFXII is doing something funky that breaks this algorithm.

**Comment by acocalypso** [comment]
@Thunder07 in your first post you mentioned that you are using an oneplus one. Which rom are you using? Cause on mine the screen stays black. Somezimes Im getting a few fps or dcs but thats it. ( Cyanogenmod 12.1 nightly)

**Comment by Thunder07** [comment]
@acocalypso I just switched to this [unoffical cm12.1 with CAF kernel](http://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-12-1-t3120259)
the CAF kernel doesn't work with non CAF ROM, and other kernels don't work with CAF kernels, so take that into consideration before making the switch.
however, CAF kernels are direct builds from Qualcomm repos, so they'll always be the most upto date you can get... but that also means no CM kernel updates.
If i'm not mistaken stock OPO uses CAF for kernel, which is why it doesnt work with AOSP/CM.

**Comment by acocalypso** [comment]
Thats my logcat maybe its usefull

08-10 16:12:06.282 I/Timeline(2755): Timeline: Activity_launch_request id:com.virtualapplications.play time:49287481
08-10 16:12:06.282 I/ActivityManager(967): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.virtualapplications.play/.MainActivity (has extras)} from uid 10019 on display 0
08-10 16:12:06.289 V/WindowManager(967): addAppToken: AppWindowToken{967a3f2 token=Token{bbc7afd ActivityRecord{398f6b54 u0 com.virtualapplications.play/.MainActivity t435}}} to stack=1 task=435 at 0
08-10 16:12:06.319 V/WindowManager(967): Adding window Window{13fc0fd8 u0 Starting com.virtualapplications.play} at 4 of 8 (after Window{16643b47 u0 com.android.dialer/com.android.dialer.DialtactsActivity})
08-10 16:12:06.383 I/ActivityManager(967): Start proc 16252:com.virtualapplications.play/u0a109 for activity com.virtualapplications.play/.MainActivity
08-10 16:12:06.641 V/WindowManager(967): Adding window Window{34071d6d u0 Locating games...} at 4 of 9 (before Window{13fc0fd8 u0 Starting com.virtualapplications.play})
08-10 16:12:06.648 V/WindowManager(967): Adding window Window{2b74ba33 u0 com.virtualapplications.play/com.virtualapplications.play.MainActivity} at 4 of 10 (before Window{34071d6d u0 Locating games...})
08-10 16:12:06.832 I/WindowManager(967): Switching to real app window: Window{2b74ba33 u0 com.virtualapplications.play/com.virtualapplications.play.MainActivity}
08-10 16:12:06.850 I/ActivityManager(967): Displayed com.virtualapplications.play/.MainActivity: +518ms
08-10 16:12:06.850 I/Timeline(967): Timeline: Activity_windows_visible id: ActivityRecord{398f6b54 u0 com.virtualapplications.play/.MainActivity t435} time:49288049
08-10 16:12:14.125 I/Timeline(16252): Timeline: Activity_launch_request id:com.virtualapplications.play time:49295325
08-10 16:12:14.125 I/ActivityManager(967): START u0 {cmp=com.virtualapplications.play/.EmulatorActivity} from uid 10109 on display 0
08-10 16:12:14.128 V/WindowManager(967): addAppToken: AppWindowToken{dff1f08 token=Token{10633cab ActivityRecord{1de28efa u0 com.virtualapplications.play/.EmulatorActivity t435}}} to stack=1 task=435 at 1
08-10 16:12:14.443 V/WindowManager(967): Adding window Window{3d3aa0c6 u0 com.virtualapplications.play/com.virtualapplications.play.EmulatorActivity} at 5 of 9 (after Window{2b74ba33 u0 com.virtualapplications.play/com.virtualapplications.play.MainActivity})
08-10 16:12:14.480 V/WindowManager(967): Adding window Window{3eeb23b4 u0 SurfaceView} at 5 of 10 (before Window{3d3aa0c6 u0 com.virtualapplications.play/com.virtualapplications.play.EmulatorActivity})
08-10 16:12:14.756 I/ActivityManager(967): Displayed com.virtualapplications.play/.EmulatorActivity: +622ms
08-10 16:12:14.756 I/Timeline(967): Timeline: Activity_windows_visible id: ActivityRecord{1de28efa u0 com.virtualapplications.play/.EmulatorActivity t435} time:49295956
08-10 16:12:14.769 I/WindowManager(967): Screen frozen for +635ms due to Window{3d3aa0c6 u0 com.virtualapplications.play/com.virtualapplications.play.EmulatorActivity}
08-10 16:12:37.912 D/Mms     (16312): checkIsFullScreenMode: the top activity is: com.virtualapplications.play.EmulatorActivity
08-10 16:14:51.635 W/PackageManager(2268): Failure retrieving resources for com.virtualapplications.play: Resource ID #0x0
08-10 16:14:52.534 I/ActivityManager(967): Killing 16252:com.virtualapplications.play/u0a109 (adj 9): remove task
08-10 16:14:52.659 I/WindowState(967): WIN DEATH: Window{3d3aa0c6 u0 com.virtualapplications.play/com.virtualapplications.play.EmulatorActivity}

**Comment by Thunder07** [comment]
@acocalypso please use pastebin.com

**Comment by acocalypso** [comment]
http://pastebin.com/qSudqNkc

**Comment by Thunder07** [comment]
@acocalypso I didn't think i needed to say this, but im asking you to use pastebin to not fill the page with it... as such you should also remove the above log.

just as well, i dont see anything useful in that log
maybe a bad copy?

**Comment by acocalypso** [comment]
Ill remove In a few mins. Gonna check the log again.
Am 10.08.2015 16:35 schrieb Thunder07 <notifications@github.com>:@acocalypso I didn't think i needed to say this, but im asking you to use pastebin to not fill the page with it... as such you should also remove the above log.

just as well, i dont see anything useful in that log
maybe a bad copy?

**Comment by acocalypso** [comment]
@Thunder07 ok its really wierd, I instaled the same Rom as you have. I did a FULL WIPE. but still I do have only a black screen. Im trying it with the german Version of FFXII

**Comment by acocalypso** [comment]
ok I hooked my Phone via ADB to my PC and Im getting a lot of this informations:

08-10 19:01:34.606: I/Adreno-ES20(16162): <validate_vertex_attrib_state:55>: validate_vertex_attrib_state: No vertex attrib is enabled in a draw call!

**Comment by Thunder07** [comment]
That's not an error the I before adreno studs for information.... 
But If you're getting that it means the game is working... 
You're probably not giving it enough time to start, it take atleast 2 mins for the cutscene to show up.

**Comment by acocalypso** [comment]
I run it over 10 mins.

**Comment by Thunder07** [comment]
@jpd002 both the warrior and both crystal issues seems to be resolved, I'm assuming the PPAC5 implementation fix that.
the "white arrow" seems to the tip of a crystal, though i don’t see the colour difference now, I'm not sure if i'm looking at the same thing :p
@acocalypso it's odd I don't imagine their will be much difference between the english and german version for it to take this long, but hopefully in time i'll get better.
