### ISSUE TITLE
Analog controller settings not working properly

### ISSUE THREAD

**Issue by micaelis72** [jpd002/Play-#1131]
## Quick summary
The possible values for analog controllers are not correctly taken, turning the use of analog controllers unreliable

## System Details
Describe the ambient being used to run Play!
Information needed:
- Operating system: Fedora Linux 35 -- Kernel 5.14.9-300.fc35.x86_64 #1 SMP Thu Sep 30 11:54:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Hardware specifications: GTX 2060 + 64Gi Mem + NVME M2 1Tb + i7-8700K
- Version of Play: 0.44, but I've also tested with the latest nightly and a custom build

## Issue Details
It seems the evdev setup doesn't allow values as uint, but only close to uint8, what clips the possible positions and turning the controller unusable with the analog sticks. I'm using a DualSense controller, but I can try to use a DualShock 3, if necessary as base for testing (Isolate if it's a DualSense issue or not)

## Screenshots/Videos
![play-controller-settings](https://user-images.githubusercontent.com/21225981/136037943-72e3809f-ed52-4928-a5f5-74fbe53b0bbe.png)

This is how is configured now, after I've tried to set my controller. As you can see, the values for Analog AXIS are little off of what they should be:

Using jstest, I've got this:
Axes:  0:-32767  1: -4387  2:-32767  3:   516  4:  -259  5:-32767  6:     0  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off
Axes:  0: 32767  1:  5934  2:-32767  3:   516  4:  -259  5:-32767  6:     0  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off

I moved the left analog controller to the extremes of the X axis, left and right. Doesn't match with I got in Play!

I can be mistaken, but seems odd the values I've got in the Controller settings on Play!
Please let me know in what I could help more. I'm searching in the code what could be wrong, but I have little experience with C/C++ code and I need more time to familiarize myself specifically with the Play!'s code!

Best,

-- Micaelis

**Comment by Dragon20C** [comment]
Hello, This is technically a duplicate post from my previous posts from the past few years(https://github.com/jpd002/Play-/issues/890), but its a good post on updating this issue. as I can tell its only a linux issue and the buttons now work correctly, used too register wrong buttons, but analog buttons like the triggers and sticks 99% of the time register wrong values. not sure how I could help as I dont know much about how linux does its controller input.

**Comment by jpd002** [comment]
Humm, one strange thing I can see from your screenshot is that the analog axis binding types are `simulatedaxisbinding`, which is used to simulate an axis with two keys (like arrow keys on the keyboard). When configuring axis inputs, if you move your analog stick, it should normally pick up `simplebinding`. This is on Windows, but it should be the same idea for Linux:

![image](https://user-images.githubusercontent.com/6760433/136237770-f7bd0406-22e8-4b23-b391-28b060c91cb7.png)

I've pushed a branch that prints key info when configuring an axis: https://github.com/jpd002/Play-/tree/linux_analog_debug. Should help in figuring out where's the issue.

**Comment by jpd002** [comment]
@Dragon20C There should be an executable in the directory you've ran CMake in. Like inside `Source\ui_qt` or something like that. You can also use the AppImage from the GitHub actions: https://github.com/jpd002/Play-/actions/runs/1312607957

**Comment by jpd002** [comment]
Thanks for that!

So, from what I can see, I think the values from the axis are not in the proper range for the config dialog. I pushed another commit that should convert the range properly. Lemme know if that works any better!

**Comment by jpd002** [comment]
Nice! Glad that helped!

In that video, are you moving the controller at all? We can see the values change in the console, just wondering if they move on their own or if you're doing something to make them change? Normally, if are not touching the analog stick, the values displayed on the console should stay around 127 (+/- 10).

Another thing to try would be to bind the dpad buttons to keyboard keys, just to rule the pov hat buttons out in case they are messing up things.

About the triggers, they might be axis buttons on your controller and for now, I don't think the emulator can handle binding axis on simple buttons atm. It's something that I could add in there (shouldn't be too hard to do).

**Comment by Dragon20C** [comment]
@jpd002 that fixed it, no problems that I could see from the initial tests I did, I think its safe to push to main!
I can finally use my controller on linux!

the last thing is implementing the triggers, but that can be left for when ever!

**Comment by Quackdoc** [comment]
Seems like this is still an issue. DS3 and DS5 neither get picked up

**Comment by davidhedlund** [comment]
> Seems like this is still an issue. DS3 and DS5 neither get picked up

Controller that are not working for me:
* DualSense

Controllers that are working for me:
* DualShock 4 v2 works
* Nintendo Switch Pro Controller

Environment:
* Play! version 0.72
* Play release: Flathub
