### ISSUE TITLE
Need for Speed Undercover - Crash and overall Graphics Issues on iOS 

### ISSUE THREAD

**Issue by nfsvsgta** [jpd002/Play-#401]
Good emulator just want to know what's causing these glitchy graphics. And when will they be fixed. And any status on dual core OpenGL etc. thanks.

**Comment by nfsvsgta** [comment]
![image](https://cloud.githubusercontent.com/assets/19260668/15105384/a2faa49a-15da-11e6-9865-1e2cd14ec9a7.jpg)
![Uploading image.jpg…]()

**Comment by nfsvsgta** [comment]
![image](https://cloud.githubusercontent.com/assets/19260668/15105396/c1a93d02-15da-11e6-94f0-4cf91f5eeab3.jpg)
Hope to play this game inshallah

**Comment by DPersonalized** [comment]
> Hope to play this game inshallah

In what?

**Comment by nfsvsgta** [comment]
"Inshallah" in Islam means " if Allah wills it"

**Comment by jpd002** [comment]
Thanks for reporting this. Quite hard to tell what's causing the problem from the screen shot alone. Probably happens on other platforms too. I'll get the game and see what's going on.

**Comment by jpd002** [comment]
Also, are the screen shots from the same game?

**Comment by nfsvsgta** [comment]
Thank you for responding. The screenshots are from two different games. The one from top are from a Japanese game. It runs but with those graphics glitches as show. The latter is nfs undercover ( my fav). It crashes after the splash screen as screenshoted. Hope to play these games fixed in the next build :) inshallah. By the way when is the next build comin ( cuz m itchin to get my hands on it, this one was impressive) and what changes/improvements will it likely have? Once again thanks

**Comment by nfsvsgta** [comment]
The Japanese game is called ps2 simple 2000 vol 68. It is a light game and good for testing. It is playable with decent fps but with the graphics issue. 
![image](https://cloud.githubusercontent.com/assets/19260668/15237285/e95d8034-18e5-11e6-98a4-4e4354f3fb8b.jpg)

**Comment by Fadi5555** [comment]
That's nice to see.
Please can you tell me what iOS device you use on?

For better testing you should use iPad Pro or air 2.

**Comment by nfsvsgta** [comment]
iPhone 6. I prefer to play these things on the go easily in fact that's the main reason so I prefer iPhone. Thanks and good luck

**Comment by nfsvsgta** [comment]
Yeah I read your threads

**Comment by nfsvsgta** [comment]
Honestly it will be a big thing for me to play PS2 on my mobile. I seriously am not fan of the games coming out on the AppStore these days and rely on ppsspp, retroarch, inds, gba4ios and of course play! Which will soon become the top of gaming in my device inshallah

**Comment by Fadi5555** [comment]
I hope so (Ameen).
Me too I'm really excited to see this emu go further and further just imagine to play resident evil 4 or any of your favorite games on your mobile or iPad with fullspeed as well as playing through PS3/4 controller. That's amazing.

So that's why we should try to help the creator of this amazing project by tell him the issues of it to become more stable on the next builds.

Let's hope next jailbreak will come by TaiG because if you can see all emu on iOS 9 has no JIT enable.
(JIT is the most important thing to run emulators in fullspeed like ppsspp,retroarch and so on).
Pangu jailbreak always comes with broken JIT unlike TaiG jailbreak.

Anyway special thanks for @jpd002 and all people who is here to help on this project.

**Comment by nfsvsgta** [comment]
Haha m still on iOS 8. Cuz after I installed icleaner from cydia, my device won't serach for update and I don't have time to sit in front of the pc to download a long update. Yes all play needs is jit and mip mapping. In other words more reliance on the gpu and it's good to beat even pcsx2. Still hopeful for the next build

**Comment by nfsvsgta** [comment]
Just a question. Why doesn't Play! Need bios. Also does Bios increase speed as it does on psx4all on iOS

**Comment by nfsvsgta** [comment]
Mr Bean is playable from 2 to 14 fps with minors graphical glitches at parts. This shows good progress of the emulator and it seems to be a game I can properly play on the emulator. Thanks for the amazing project and keep up the good work ( all eyes on the next build) 
![image](https://cloud.githubusercontent.com/assets/19260668/15271992/dcf76b54-1a7d-11e6-800f-504e79814a3f.jpg)

**Comment by nfsvsgta** [comment]
On iOS

**Comment by jpd002** [comment]
Play! handles BIOS system calls internally (HLE style). Also, using a BIOS isn't supported.

Thanks for the screen shot, I had no idea that game worked.

**Comment by nfsvsgta** [comment]
Yep it fully works

**Comment by nfsvsgta** [comment]
Another test. Need for speed carbon ps2 demo version. This does not work on pcsx2 properly and in play! On iPhone 6 it stays on this splash screen. Woah I was just that close to playin my dream game on iPhone. Looking forward to play such games. In next build?
![image](https://cloud.githubusercontent.com/assets/19260668/15396220/7f29729a-1df4-11e6-82f3-3e342edd0770.jpg)

**Comment by nfsvsgta** [comment]
@jpd002 Will memory card be added to play and what's the current status. When will the next build come and the changes? Thanks

**Comment by nfsvsgta** [comment]
![image](https://cloud.githubusercontent.com/assets/19260668/16706279/7a1bf71c-45bf-11e6-9359-c32554ff324e.jpg)
Controls not responding in nfs carbon. Though now this goes to menu. Only x o square triangle don't respond. Directional and start do. Further broken graphics

**Comment by nfsvsgta** [comment]
Nfs undercover now runs on pc. Will check it on iOS

**Comment by nfsvsgta** [comment]
All nfs seems to work. @jpd002 it seems u have made all nfs compatible. Only xo etc don't work and broken graphics

**Comment by jpd002** [comment]
Humm, that's odd, I can't get my version of NFS Carbon (SLUS21493) to work. I'll have to try the EU version to see if there's any difference.

**Comment by nfsvsgta** [comment]
The eu version works for all the games. Eu and U.S. I guess

**Comment by jpd002** [comment]
Interesting, thanks for the feedback!

**Comment by nfsvsgta** [comment]
And oh the version of nfs carbon is the demo version with more enhanced graphics as all say. Also since undercover works which i think is European version all nfs should work. In the demo only xo etc don't respond and the graphics are broken. Further in pc undercover can't seem to recognise the controller and I currently don't have 3.8 gb on my iPhone 6 to test undercover. But will soon do

**Comment by nfsvsgta** [comment]
@jpd002 just an update. Nfs undercover still crashes on startup on iOS but it works on pc now unlike the same crash before

**Comment by nfsvsgta** [comment]
Need for speed underground in game on iOS 
![image](https://cloud.githubusercontent.com/assets/19260668/17361639/e93118f6-598a-11e6-93a6-24f85ef53a53.jpg)

**Comment by Fadi5555** [comment]
@nfsvsgta nice news. Well the emu need to fix some graphics issues and enhance the speed as well. In the meantime @jpd002 is not present these days.
Hopefully we'll continue to this work and have daily fixing.

**Comment by nfsvsgta** [comment]
@jpd002 after your recent commits, these broken graphics should be fixed right?

**Comment by jpd002** [comment]
Not sure, the missing polygons could be fixed with the VU integer stuff that was committed recently, but the garbled textures is most likely caused by something else.

**Comment by nfsvsgta** [comment]
Right well good luck

**Comment by Deathlock47** [comment]
@jpd002 Any ideas on broken polygons and triangles? The problem still seems to be present
![screenshot_20161211-230240](https://cloud.githubusercontent.com/assets/22158671/21105404/23385bbe-c09b-11e6-9637-900b4fdbdf59.png)
![screenshot_20161023-221203](https://cloud.githubusercontent.com/assets/22158671/21105365/044ec22e-c09b-11e6-856a-4b7e6cfe819b.png)

**Comment by jpd002** [comment]
The latest changes to the way the CLIP register is handled might help. They'll be in the next official build.

**Comment by iOS4all** [comment]
@jpd002 is this going to fix graphical issues in some games as well or just specific on this game only?

**Comment by Deathlock47** [comment]
Sadly, not only aren't the graphics fixed but the whole series no longer goes ingame, freezing at loading screen
![screenshot_20170124-233854](https://cloud.githubusercontent.com/assets/22158671/22292314/9d039a9c-e31b-11e6-870d-dbebfe16e065.png)
![screenshot_20170124-234212](https://cloud.githubusercontent.com/assets/22158671/22292269/7bc5f708-e31b-11e6-8896-928c2eae4e35.png)
![screenshot_20170124-221331](https://cloud.githubusercontent.com/assets/22158671/22292330/b09a6c20-e31b-11e6-86d1-d8d22d03c697.png)

**Comment by jpd002** [comment]
Many things listed here have been fixed. Would probably be interesting to retest the games.

Example:
![image](https://user-images.githubusercontent.com/6760433/121062725-7612de00-c793-11eb-8713-2d3cb980e050.png)
